#!/bin/bash -eux
source "$(dirname $0)/bin/conf"

#[ "$USER" = "root" ]


## INSTALL SYSTEM
rsync -av --delete "$(dirname $0)/bin/" "$appdir"



## CLONE REPO
rm -rf "${contentsdir:?}"
cd "$wwwdir"
git clone "https://github.com/$contents_owner/$contents"
chown www-data:www-data "$contentsdir" -R
